include: package:very_good_analysis/analysis_options.yaml

format:
  line_length: 90

linter:
  rules:
    public_member_api_docs: false
    one_member_abstracts: false
    sort_pub_dependencies: false
analyzer:
  errors:
    lines_longer_than_80_chars: ignore
