// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;

import 'src/features/library/data/models/video_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5863521568893898851),
    name: 'VideoModel',
    lastPropertyId: const obx_int.IdUid(9, 6494778161434609773),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5558282081303751607),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5866273296486531365),
        name: 'youtubeId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 4065306276962701119),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6861697640710049424),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1488671335603469764),
        name: 'channelName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5002840078807243702),
        name: 'thumbnailUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 9033770111852105582),
        name: 'durationSeconds',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8085222500629745118),
        name: 'lastWatchedPositionSeconds',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4932942474933510134),
        name: 'addedAt',
        type: 12,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6494778161434609773),
        name: 'lastPlayedAt',
        type: 12,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
obx.Store openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) {
  return obx.Store(
    getObjectBoxModel(),
    directory: directory,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 5863521568893898851),
    lastIndexId: const obx_int.IdUid(1, 4065306276962701119),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    VideoModel: obx_int.EntityDefinition<VideoModel>(
      model: _entities[0],
      toOneRelations: (VideoModel object) => [],
      toManyRelations: (VideoModel object) => {},
      getId: (VideoModel object) => object.id,
      setId: (VideoModel object, int id) {
        object.id = id;
      },
      objectToFB: (VideoModel object, fb.Builder fbb) {
        final youtubeIdOffset = fbb.writeString(object.youtubeId);
        final titleOffset = fbb.writeString(object.title);
        final channelNameOffset = fbb.writeString(object.channelName);
        final thumbnailUrlOffset = fbb.writeString(object.thumbnailUrl);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, youtubeIdOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, channelNameOffset);
        fbb.addOffset(4, thumbnailUrlOffset);
        fbb.addInt64(5, object.durationSeconds);
        fbb.addInt64(6, object.lastWatchedPositionSeconds);
        fbb.addInt64(7, object.addedAt.microsecondsSinceEpoch * 1000);
        fbb.addInt64(
          8,
          object.lastPlayedAt == null
              ? null
              : object.lastPlayedAt!.microsecondsSinceEpoch * 1000,
        );
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final lastPlayedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final youtubeIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final channelNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final thumbnailUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final durationSecondsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final addedAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0) / 1000)
              .round(),
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final lastWatchedPositionSecondsParam = const fb.Int64Reader()
            .vTableGet(buffer, rootOffset, 16, 0);
        final lastPlayedAtParam = lastPlayedAtValue == null
            ? null
            : DateTime.fromMicrosecondsSinceEpoch(
                (lastPlayedAtValue / 1000).round(),
              );
        final object = VideoModel(
          youtubeId: youtubeIdParam,
          title: titleParam,
          channelName: channelNameParam,
          thumbnailUrl: thumbnailUrlParam,
          durationSeconds: durationSecondsParam,
          addedAt: addedAtParam,
          id: idParam,
          lastWatchedPositionSeconds: lastWatchedPositionSecondsParam,
          lastPlayedAt: lastPlayedAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [VideoModel] entity fields to define ObjectBox queries.
class VideoModel_ {
  /// See [VideoModel.id].
  static final id = obx.QueryIntegerProperty<VideoModel>(
    _entities[0].properties[0],
  );

  /// See [VideoModel.youtubeId].
  static final youtubeId = obx.QueryStringProperty<VideoModel>(
    _entities[0].properties[1],
  );

  /// See [VideoModel.title].
  static final title = obx.QueryStringProperty<VideoModel>(
    _entities[0].properties[2],
  );

  /// See [VideoModel.channelName].
  static final channelName = obx.QueryStringProperty<VideoModel>(
    _entities[0].properties[3],
  );

  /// See [VideoModel.thumbnailUrl].
  static final thumbnailUrl = obx.QueryStringProperty<VideoModel>(
    _entities[0].properties[4],
  );

  /// See [VideoModel.durationSeconds].
  static final durationSeconds = obx.QueryIntegerProperty<VideoModel>(
    _entities[0].properties[5],
  );

  /// See [VideoModel.lastWatchedPositionSeconds].
  static final lastWatchedPositionSeconds =
      obx.QueryIntegerProperty<VideoModel>(_entities[0].properties[6]);

  /// See [VideoModel.addedAt].
  static final addedAt = obx.QueryDateNanoProperty<VideoModel>(
    _entities[0].properties[7],
  );

  /// See [VideoModel.lastPlayedAt].
  static final lastPlayedAt = obx.QueryDateNanoProperty<VideoModel>(
    _entities[0].properties[8],
  );
}
